name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Fork with Upstream
        uses: tgymnich/fork-sync@v1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: byte-capsule
          repo: Toffee-Channels-Link-Headers
          base: main
          head: main
          force: true
